<?php

namespace AppBundle\Repository;

/**
 * ReadByRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadByRepository extends \Doctrine\ORM\EntityRepository
{
}
