# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
            in_memory:
                memory:
                    users:
                        kk:
                            password: 1234
                            roles: 'ROLE_USER'

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        usuarios:
          pattern: ^/
          anonymous: ~
          provider: in_memory
          form_login:
            check_path: /
            login_path: /
        kk:
          pattern: ^/home
          http_basic: ~
        main:
                  anonymous: ~
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/home, roles: ROLE_USER }
